export default {
  // Dashboard
  MenuImageMap: require("../assets/images/menu/map.png"),
  MenuImageMarket: require("../assets/images/menu/market-inactive.png"),
  MenuImagePrizes: require("../assets/images/menu/prize.png"),
  MenuImageProfile: require("../assets/images/menu/profile.png"),
  MenuImageWallet: require("../assets/images/menu/wallet.png"),
  MenuImageScanner: require("../assets/images/menu/scanner.png"),

  // WelcomeScreen
  Google: require("../assets/images/icons/google.png"),
  Apple: require("../assets/images/icons/apple.png"),
  Facebook: require("../assets/images/icons/facebook.png"),
  WelcomeCarousel1: require("../assets/images/welcome/1.png"),
  WelcomeCarousel2: require("../assets/images/welcome/2.png"),
  WelcomeCarousel3: require("../assets/images/welcome/3.png"),
  WelcomeCarousel4: require("../assets/images/welcome/4.png"),

  // Backgrounds
  BackgroundCard: require("../assets/backgrounds/card.png"),
  // require("../assets/backgrounds/cards_wn.png"),
  BackgroundCards: require("../assets/backgrounds/cards.png"),
  // require("../assets/backgrounds/details_wn.png"),
  BackgroundDetails: require("../assets/backgrounds/details.png"),
  BackgroundHomeWn: require("../assets/backgrounds/home_wn.png"),
  BackgroundHome: require("../assets/backgrounds/home.png"),
  BackgroundLogoutWn: require("../assets/backgrounds/logout_wn.png"),
  BackgroundLogout: require("../assets/backgrounds/logout.png"),
  // require("../assets/backgrounds/nearby_wn.png"),
  BackgroundNearby: require("../assets/backgrounds/nearby.png"),
  BackgroundPasswordWn: require("../assets/backgrounds/password_wn.png"),
  BackgroundPassword: require("../assets/backgrounds/password.png"),
  // require("../assets/backgrounds/plain_wn.png"),
  Background: require("../assets/backgrounds/plain.png"),
  BackgroundPrizesWn: require("../assets/backgrounds/prizes_wn.png"),
  BackgroundPrizes: require("../assets/backgrounds/prizes.png"),
  BackgroundProfileWn: require("../assets/backgrounds/profile_wn.png"),
  BackgroundProfile: require("../assets/backgrounds/profile.png"),
  BackgroundTOSWn: require("../assets/backgrounds/tos_wn.png"),
  BackgroundTOS: require("../assets/backgrounds/tos.png"),
  BackgroundWalletWn: require("../assets/backgrounds/wallet_wn.png"),
  BackgroundWallet: require("../assets/backgrounds/wallet.png"),

  // Logos
  StamperLogo: require("../assets/logos/stamper_logo_300px.png"),
  StamperLogoEn: require("../assets/logos/stamper_logo_300px_en.png"),
  StamperLogoPl: require("../assets/logos/stamper_logo_2x.png"),
  // require("../assets/logos/stamper_logo_3x.png"),
  // require("../assets/logos/stamper_logo_4x.png"),
  StamperSygnet: require("../assets/logos/stamper_sygnet_300px.png"),
  StamperSygnet2x: require("../assets/logos/stamper_sygnet_2x.png"),
  // require("../assets/logos/stamper_sygnet_3x.png"),
  // require("../assets/logos/stamper_sygnet_4x.png"),

  // Loaders
  MapLoader: require("../assets/loaders/map.gif"),
  RewardsLoader: require("../assets/loaders/rewards.gif"),
  WalletLoader: require("../assets/loaders/wallet.gif"),
  Spinner: require("../assets/loaders/spinner.gif"),

  Success: require("../assets/images/success.png"),
  Error: require("../assets/images/error.png"),
  AppIcon: require("../assets/images/icon.png"),
  Plus: require("../assets/images/plus.png"),
  Delete: require("../assets/images/delete.png"),
  Qr: require("../assets/images/qr.png"),
  Splash: require("../assets/images/splash.png"),
  AlreadyInWallet: require("../assets/images/icons/already-in-wallet.png"),
  Balance: require("../assets/images/icons/balance.png"),
  Email: require("../assets/images/icons/email.png"),
  LocationIndicator: require("../assets/images/icons/location_indicator.png"),
  Newsletter: require("../assets/images/icons/newsletter.png"),
  NextIcon: require("../assets/images/icons/next_icon.png"),
  Wallet: require("../assets/images/icons/wallet.png"),
  Offline: require("../assets/offline.png"),

  // Success animations
  EarnedReward: require("../assets/success/earned_reward.gif"),
  ReceivedReward: require("../assets/success/received_reward.gif"),
  CardAdd: require("../assets/success/card_add.gif"),
  StampAdd: require("../assets/success/stamp_add.gif"),
  StampSubtract: require("../assets/success/stamp_subtract.gif"),
};
