# https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html
# https://confluence.atlassian.com/bitbucket/environment-variables-794502608.html
---
image: node:alpine

definitions:
  caches:
    npm: ~/.npm
    jest: .jest

  steps:
    - step: &validate-and-test
        name: Validate and test
        caches:
          - npm
          - jest
        script:
          - npm ci
        # - npm test

pipelines:
  default:
    - step: *validate-and-test

  branches:
    master:
      - step: *validate-and-test
      - step:
          name: Deploy to Expo
          deployment: production
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            - npx expo publish --non-interactive

    development:
      - step: *validate-and-test
      - step:
          name: Deploy to Expo
          deployment: staging
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            - npx expo publish --non-interactive --release-channel staging

  pull-requests:
    # This runs as default for any branch not elsewhere defined
    "**":
      - step: *validate-and-test

    # Any branch with a feature prefix
    feature/*:
      - step: *validate-and-test
      - step:
          name: Deploy to Expo
          deployment: test
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            - npx expo publish --non-interactive --release-channel feature.$BITBUCKET_PR_ID
