---
image: node:alpine

definitions:
  caches:
    npm: ~/.npm
    jest: .jest

pipelines:
  default:
    - step:
        name: Install dependencies
        caches:
          - npm
        script:
          - apk add --no-cache bash
          - npm ci
          - npm install -g expo-cli
          - npm install
  #    - step:
  #        name: Run tests
  #        caches:
  #          - jest
  #        script:
  #          - npm test

  branches:
    development:
      - step:
          name: Install dependencies
          caches:
            - npm
          script:
            - npm ci
      #      - step:
      #          name: Run tests
      #          caches:
      #            - jest
      #          script:
      #            - npm test
      - step:
          name: Deploy to Expo
          deployment: test
          caches:
            - npm
          script:
            - apk add --no-cache bash
            - npm ci
            - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
            - npx expo publish --non-interactive
